import THREE from "../three.js";
import {Generator} from "../world/Generator.js";
export class NetworkManager{constructor(game){this.game=game;this.ws=null;this.enabled=false;this.hosting=false;this.serverUrl="";this.id=null;this.name=`Игрок_${Math.floor(100+Math.random()*900)}`;this.remote=new Map;this.lastSend=0;this.connected=false}
connect(url,hosting=false){this.enabled=true;this.hosting=hosting;this.serverUrl=url||"";if(this.ws)this.disconnect();if(!url)return this.setStatus("Укажи адрес сервера");try{this.ws=new WebSocket(url)}catch{return this.setStatus("Неверный адрес сервера")}this.setStatus("Подключение…");this.ws.onopen=()=>{this.connected=true;this.setStatus("Подключено");this.send({type:"join",name:this.name,seed:this.game.world.cfg.WORLD.SEED,host:this.hosting});if(this.hosting)this.syncHostWorld();
this.game.network?.chatLine(this.hosting?"★ Ты открыл свой мир для локальной сети":"Подключение к локальному миру…");this.updateHUD()};this.ws.onmessage=e=>{try{this.handle(JSON.parse(e.data))}catch{}};this.ws.onerror=()=>this.setStatus("Ошибка соединения");this.ws.onclose=()=>{this.connected=false;this.ws=null;this.clearRemote();this.setStatus("Отключено");this.updateHUD()}}
disconnect(){this.enabled=false;this.hosting=false;if(this.ws)this.ws.close();this.ws=null;this.connected=false;this.clearRemote();this.updateHUD()}
send(d){if(this.ws?.readyState===WebSocket.OPEN)this.ws.send(JSON.stringify(d))}
tick(dt){if(!this.enabled||!this.connected)return;this.lastSend+=dt;if(this.lastSend<.08)return;this.lastSend=0;const p=this.game.player.pos;this.send({type:"state",x:p.x,y:p.y,z:p.z,ry:this.game.controls.yaw})}
blockChanged(x,y,z,id){if(this.enabled&&this.connected)this.send({type:"block",x,y,z,id})}
syncHostWorld(){if(!this.hosting||!this.connected)return;this.send({type:"host_snapshot",seed:this.game.world.cfg.WORLD.SEED,blocks:this.game.world.serializeChanges()})}
chat(text){const t=text.trim();if(this.enabled&&this.connected&&t)this.send({type:"chat",text:t})}
handle(m){if(m.type==="welcome"){this.id=m.id;if(Number.isFinite(Number(m.seed)) && !this.hosting && this.game.world.chunks.size===0){this.game.world.cfg.WORLD.SEED=Number(m.seed);this.game.world.gen=new Generator(Number(m.seed));}this.game.world.loadChanges(m.blocks||[]);this.name=m.name||this.name;this.renderPlayers(m.players||[]);return}if(m.type==="player_join"){this.upsert(m.player);this.chatLine(`+ ${m.player.name} подключился`);return}if(m.type==="player_leave"){this.remove(m.id);this.chatLine(`− Игрок покинул мир`);return}if(m.type==="state"){if(m.id!==this.id)this.upsert(m);return}if(m.type==="block"){this.game.world.setBlock(m.x,m.y,m.z,m.id,false);return}if(m.type==="snapshot"||m.type==="world_snapshot"){for(const b of m.blocks||[])this.game.world.setBlock(b.x,b.y,b.z,b.id,false);return}if(m.type==="chat")this.chatLine(`${m.name}: ${m.text}`)}
renderPlayers(list){this.clearRemote();for(const p of list)if(p.id!==this.id)this.upsert(p)}
upsert(p){if(!p?.id)return;let r=this.remote.get(p.id);if(!r){const g=new THREE.Group,body=new THREE.Mesh(new THREE.BoxGeometry(.6,1,.35),new THREE.MeshLambertMaterial({color:0x4e79a7})),head=new THREE.Mesh(new THREE.BoxGeometry(.48,.48,.48),new THREE.MeshLambertMaterial({color:0xc99f7a}));body.position.y=.65;head.position.y=1.38;g.add(body,head);const tag=this.makeTag(p.name||"Игрок");tag.position.y=2.05;g.add(tag);this.game.scene.add(g);r={group:g,target:new THREE.Vector3(),name:p.name};this.remote.set(p.id,r)}r.target.set(p.x,p.y,p.z);r.group.rotation.y=p.ry||0;r.name=p.name||r.name}
update(dt){for(const r of this.remote.values())r.group.position.lerp(r.target,Math.min(1,dt*12))}
makeTag(text){const c=document.createElement("canvas");c.width=256;c.height=64;const x=c.getContext("2d");x.fillStyle="rgba(0,0,0,.65)";x.fillRect(4,8,248,48);x.fillStyle="#fff";x.font="bold 22px sans-serif";x.textAlign="center";x.fillText(text.slice(0,20),128,40);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(1.8,.45,1);return s}
remove(id){const r=this.remote.get(id);if(r){this.game.scene.remove(r.group);r.group.traverse(o=>{o.geometry?.dispose();if(o.material?.map)o.material.map.dispose();o.material?.dispose()});this.remote.delete(id)}}clearRemote(){for(const id of [...this.remote.keys()])this.remove(id)}
setStatus(t){const e=document.getElementById("multiStatus");if(e)e.textContent=t}chatLine(t){const e=document.getElementById("chatLog");if(!e)return;const r=document.createElement("div");r.textContent=t;e.appendChild(r);while(e.children.length>30)e.firstChild.remove();e.scrollTop=e.scrollHeight}updateHUD(){const b=document.getElementById("onlineHud"),c=document.getElementById("onlineCount");if(!b)return;b.classList.toggle("hidden",!this.connected);if(c)c.textContent=this.connected?`ONLINE • ${this.remote.size+1}`:"OFFLINE";const l=document.getElementById("playerList");if(l)l.textContent=this.connected?`Игроков в мире: ${this.remote.size+1}`:""}}
