import {CONFIG} from "../config.js";
const CONFIG_AIRDROP_GROUND=(w,x,z)=>{for(let y=w.cfg.WORLD.HEIGHT-2;y>1;y--){const id=w.getBlock(x,y,z);if(INFO[id]?.solid)return y;}return -1};
import {BLOCK,ITEM,INFO,ICON} from "../world/Block.js";
const key=(p)=>`${p.x|0},${p.y|0},${p.z|0}`;
export class SurvivalSystems{
 constructor(game){this.game=game;this.chests=new Map();this.furnaces=new Map();this.crops=new Map();this.xp=0;this.level=1;this.achievements=new Set();this.lastWorldTick=0;this.eventTimer=55+Math.random()*35;this.airDrops=0}
 award(xp=0,achievement=""){this.xp+=xp;while(this.xp>=this.level*100){this.xp-=this.level*100;this.level++;this.toast(`Уровень ${this.level}!`);this.game.particles?.burst(this.game.player.pos.clone().add({x:0,y:1,z:0}),0xffd34d,18)}if(achievement&&!this.achievements.has(achievement)){this.achievements.add(achievement);this.toast(`🏆 ${achievement}`)}}
 toast(t){const el=document.getElementById("saveToast");if(!el)return;el.textContent=t;el.classList.add("show");clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove("show"),1800)}
 placed(id,p){const k=key(p);if(id===BLOCK.CHEST&&!this.chests.has(k))this.chests.set(k,Array.from({length:18},()=>({id:0,count:0})));if(id===BLOCK.FURNACE&&!this.furnaces.has(k))this.furnaces.set(k,{input:0,progress:0,output:0});if(id===BLOCK.WHEAT)this.crops.set(k,{age:0,grow:0})}
 removed(id,p){const k=key(p);if(id===BLOCK.CHEST)this.chests.delete(k);if(id===BLOCK.FURNACE)this.furnaces.delete(k);if(id===BLOCK.BED)this.game.bedRespawnKey=null;if(id===BLOCK.WHEAT)this.crops.delete(k)}
 tick(dt){this.lastWorldTick+=dt;this.eventTimer-=dt;if(this.eventTimer<=0){this.eventTimer=110+Math.random()*100;this.spawnAirdrop()}if(this.lastWorldTick<1)return;this.lastWorldTick=0;for(const [k,c] of this.crops){const [x,y,z]=k.split(',').map(Number),light=this.game.world.getBlock(x,y+1,z);c.grow+=INFO[light]?.emissive?1.8:.65;if(c.grow>=12){c.grow=0;c.age=Math.min(3,c.age+1)}}for(const f of this.furnaces.values()){if(!f.input)continue;f.progress+=1;if(f.progress>=5){f.progress=0;f.output=Math.min(64,f.output+1);f.input=0;this.award(4,"Первый слиток")}}}

 spawnAirdrop(){const g=this.game,p=g.player,w=g.world;for(let attempt=0;attempt<18;attempt++){const a=Math.random()*Math.PI*2,r=24+Math.random()*26,x=Math.floor(p.pos.x+Math.cos(a)*r),z=Math.floor(p.pos.z+Math.sin(a)*r);let y=CONFIG_AIRDROP_GROUND(w,x,z);if(y<2||y>=w.cfg.WORLD.HEIGHT-2)continue;if(Math.hypot(x-p.pos.x,z-p.pos.z)<18)continue;const base=w.getBlock(x,y,z),above=w.getBlock(x,y+1,z);if(!INFO[base]?.solid||above!==BLOCK.AIR)continue;const ck=`${x},${y+1},${z}`;if(this.chests.has(ck))continue;w.setBlock(x,y+1,z,BLOCK.CHEST);this.chests.set(ck,Array.from({length:18},()=>({id:0,count:0})));const slots=this.chests.get(ck);let h=(x*73856093^z*19349663^Math.floor(g.time*17))|0;const loot=[{id:ITEM.APPLE,count:2},{id:ITEM.BREAD,count:2},{id:BLOCK.IRON,count:4},{id:BLOCK.COAL,count:6},{id:ITEM.LEATHER,count:4},{id:ITEM.WOOL,count:3},{id:ITEM.IRON_INGOT,count:2},{id:ITEM.SWORD,count:1},{id:ITEM.SHIELD,count:1},{id:ITEM.WOOD_PICK,count:1}];for(let i=0;i<5;i++){const q=loot[Math.abs(h+i*31)%loot.length],slot=slots[i];slot.id=q.id;slot.count=q.count}this.airDrops++;g.network?.blockChanged?.(x,y+1,z,BLOCK.CHEST);g.particles?.burst(g.vec(x+.5,y+1.5,z+.5),0xffd34d,24);this.toast(`📦 АВАРИЙНЫЙ СБРОС №${this.airDrops}: новый сундук появился рядом`);this.award(15,"Первый аварийный сброс");return true}return false}
 interact(hit){if(!hit)return false;const id=hit.id,p=hit.block;if(id===BLOCK.CHEST){this.openChest(key(p));return true}if(id===BLOCK.FURNACE){this.openFurnace(key(p));return true}if(id===BLOCK.BED){this.sleepInBed(p);return true}if(id===BLOCK.WHEAT){const c=this.crops.get(key(p));if(c?.age>=3){this.game.world.setBlock(p.x,p.y,p.z,BLOCK.AIR);this.crops.delete(key(p));this.game.inventory.add(ITEM.WHEAT,1+Math.floor(Math.random()*2));if(Math.random()<.65)this.game.inventory.add(ITEM.SEEDS,1);this.award(8,"Первый урожай");this.game.particles.burst(this.game.vec(p.x+.5,p.y+.5,p.z+.5),0xe5c24d,10);return true}}return false}
 sleepInBed(p){const g=this.game, phase=(g.time%CONFIG.DAY.LENGTH)/CONFIG.DAY.LENGTH, night=phase<.25||phase>.75;if(!night){this.toast("🛏️ Кровать можно использовать для сна ночью");return}g.bedRespawnKey=key(p);g.respawnPoint={x:p.x+.5,y:p.y+1.02,z:p.z+.5};g.time=Math.floor(CONFIG.DAY.LENGTH*.25)+0.01;g.save();g.particles?.burst(g.vec(p.x+.5,p.y+1,z+.5),0xffffff,16);this.award(10,"Первый сон");this.toast("☀️ Выспался! Точка возрождения установлена.")}

 openChest(k){const panel=document.getElementById("containerPanel");if(!this.chests.has(k))this.chests.set(k,Array.from({length:18},()=>({id:0,count:0})));const slots=this.chests.get(k);if(!slots.some(s=>s.id)){this.seedChest(slots,k)}panel.classList.remove("hidden");panel.dataset.kind="chest";panel.dataset.key=k;document.getElementById("containerTitle").textContent="СУНДУК";document.getElementById("containerSubtitle").textContent="18 СЛОТОВ • ЛУТ";this.renderContainer(slots)}
 openFurnace(k){const panel=document.getElementById("containerPanel");panel.classList.remove("hidden");panel.dataset.kind="furnace";panel.dataset.key=k;document.getElementById("containerTitle").textContent="ПЕЧЬ";document.getElementById("containerSubtitle").textContent="ПЕРЕПЛАВКА • МАТЕРИАЛЫ";this.renderFurnace(this.furnaces.get(k)||{input:0,progress:0,output:0})}
 close(){document.getElementById("containerPanel")?.classList.add("hidden")}
 seedChest(slots,k){let h=0;for(let i=0;i<k.length;i++)h=(h*31+k.charCodeAt(i))|0;const loot=[{id:ITEM.APPLE,count:1+(Math.abs(h)%3)},{id:ITEM.BREAD,count:1+(Math.abs(h>>3)%2)},{id:ITEM.STICK,count:2+(Math.abs(h>>5)%5)},{id:BLOCK.COAL,count:2+(Math.abs(h>>7)%5)},{id:BLOCK.IRON,count:1+(Math.abs(h>>9)%4)},{id:ITEM.LEATHER,count:2+(Math.abs(h>>11)%4)},{id:ITEM.WOOL,count:3},{id:ITEM.WOOD_PICK,count:1},{id:ITEM.SWORD,count:1},{id:ITEM.LEATHER_HELM,count:1},{id:ITEM.LEATHER_CHEST,count:1},{id:ITEM.LEATHER_LEGS,count:1},{id:ITEM.LEATHER_BOOTS,count:1},{id:ITEM.SHIELD,count:1}];let n=3+(Math.abs(h)%4);for(let i=0;i<n;i++){const x=loot[Math.abs(h+i*17)%loot.length];const slot=slots[i];slot.id=x.id;slot.count=x.count}}
 renderContainer(slots){const el=document.getElementById("containerGrid");if(!el)return;el.innerHTML="";slots.forEach((s,idx)=>{const b=document.createElement("button");b.type="button";b.className="containerSlot"+(s.id?" filled":"");b.innerHTML=`<span>${ICON[s.id]||"·"}</span><small>${s.count||""}</small>`;b.title=s.id?INFO[s.id]?.name||"Предмет":"Пусто";b.onclick=()=>{if(!s.id)return;const free=this.game.inventory.add(s.id,s.count);if(free){s.id=0;s.count=0;this.game.audio?.pickup?.();this.renderContainer(slots)}};el.appendChild(b)});const selected=this.game.inventory.selectedItem(),si=document.getElementById("containerSelected");if(si)si.innerHTML=selected?.id?`<strong>${ICON[selected.id]||"·"} ${INFO[selected.id]?.name||"Предмет"}</strong><span>Слот ${this.game.inventory.selected+1} • ${selected.count||0} шт.</span>`:"Пусто"}
 depositToChest(){const panel=document.getElementById("containerPanel"),ch=this.chests.get(panel.dataset.key),s=this.game.inventory.selectedItem();if(!ch||!s?.id)return;let slot=ch.find(x=>x.id===s.id&&x.count<64)||ch.find(x=>!x.id);if(!slot)return;if(!this.game.inventory.remove(s.id,1))return;slot.id=s.id;slot.count=(slot.count||0)+1;this.game.audio?.block?.();this.renderContainer(ch)}
 depositAllToChest(){const panel=document.getElementById("containerPanel"),ch=this.chests.get(panel.dataset.key),s=this.game.inventory.selectedItem();if(!ch||!s?.id)return;let moved=0;while(this.game.inventory.has(s.id,1)){const slot=ch.find(x=>x.id===s.id&&x.count<64)||ch.find(x=>!x.id);if(!slot)break;if(!this.game.inventory.remove(s.id,1))break;slot.id=s.id;slot.count=(slot.count||0)+1;moved++}if(moved)this.game.audio?.block?.();this.renderContainer(ch)}
 renderFurnace(f){const el=document.getElementById("containerGrid");el.innerHTML=`<div class="furnaceInfo">Вход: ${ICON[f.input]||"·"} ${f.input?INFO[f.input]?.name:"пусто"}<br>Прогресс: ${Math.floor(f.progress/5*100)}%<br>Выход: ⚙ ${f.output}</div>`;const a=document.createElement("button");a.className="containerAction";a.textContent="Плавить железную руду";a.onclick=()=>{if(!f.input&&f.output<64&&this.game.inventory.remove(BLOCK.IRON,1)){f.input=BLOCK.IRON;f.progress=0;this.renderFurnace(f)}};el.appendChild(a);const b=document.createElement("button");b.className="containerAction";b.textContent="Забрать слитки";b.onclick=()=>{if(f.output){this.game.inventory.add(ITEM.IRON_INGOT,f.output);f.output=0;this.renderFurnace(f)}};el.appendChild(b)}
 serialize(){return{chests:[...this.chests],furnaces:[...this.furnaces],crops:[...this.crops],xp:this.xp,level:this.level,achievements:[...this.achievements],airDrops:this.airDrops,eventTimer:this.eventTimer}}
 deserialize(d){if(!d)return;this.chests=new Map(d.chests||[]);this.furnaces=new Map(d.furnaces||[]);this.crops=new Map(d.crops||[]);this.xp=d.xp||0;this.level=d.level||1;this.achievements=new Set(d.achievements||[]);this.airDrops=d.airDrops||0;this.eventTimer=Number.isFinite(Number(d.eventTimer))?Number(d.eventTimer):90;}
}
