import THREE from "../three.js";
import {BLOCK,INFO} from "../world/Block.js";
export class Player{
 constructor(camera,world,controls,cfg){this.camera=camera;this.world=world;this.controls=controls;this.cfg=cfg;this.pos=new THREE.Vector3(0,70,0);this.vel=new THREE.Vector3();this.onGround=false;this.health=20;this.hunger=20;this.inventory=null;this.walkTime=0;this.sprint=false;this.stamina=100;this.xp=0;this.level=1;this.regenTimer=0;this.effects={haste:0,miningFatigue:0,aquaAffinity:false};this.handGroup=new THREE.Group();this.handGroup.position.set(.43,-.38,-.82);this.camera.add(this.handGroup);this.handArm=null;this.heldMesh=null;this.heldId=0;this.updateHeldItem(0)}
 setInventory(inv){this.inventory=inv;this.updateHeldItem(inv?.selectedItem?.()?.id||0)}
 updateHeldItem(id=0){if(this.heldId===id&&this.handArm)return;this.heldId=id;this.handGroup.clear();const skin=new THREE.MeshLambertMaterial({color:0xc18d6e});this.handArm=new THREE.Mesh(new THREE.BoxGeometry(.22,.65,.22),skin);this.handArm.rotation.z=-.18;this.handGroup.add(this.handArm);if(!id||!INFO[id])return;const info=INFO[id],color=info.solid?0x777777:(info.tool?0xb0b0b0:0x8aa06b);const item=new THREE.Mesh(new THREE.BoxGeometry(info.tool?.includes?.("pick")?.5:.28,.28,.18),new THREE.MeshLambertMaterial({color}));item.position.set(.05,.2,-.12);item.rotation.z=-.25;this.handGroup.add(item);this.heldMesh=item}

 solid(x,y,z){return !!INFO[this.world.getBlock(Math.floor(x),Math.floor(y),Math.floor(z))]?.solid}
 collides(p){const r=.29,h=1.78;for(let x=Math.floor(p.x-r);x<=Math.floor(p.x+r);x++)for(let y=Math.floor(p.y+.02);y<=Math.floor(p.y+h);y++)for(let z=Math.floor(p.z-r);z<=Math.floor(p.z+r);z++)if(this.solid(x,y,z))return true;return false}
 jump(){const grounded=this.onGround||INFO[this.world.getBlock(Math.floor(this.pos.x),Math.floor(this.pos.y-.12),Math.floor(this.pos.z))]?.solid;if(!grounded)return false;this.vel.y=this.cfg.PLAYER.JUMP;this.onGround=false;return true}
 move(dt){const c=this.controls,k=c.keys;const wantsSprint=!!k.ShiftLeft;const movingInput=!!(k.KeyW||k.KeyA||k.KeyS||k.KeyD);const canSprint=wantsSprint&&movingInput&&this.stamina>1;const sp=canSprint?this.cfg.PLAYER.SPRINT_SPEED:this.cfg.PLAYER.WALK_SPEED;let dx=0,dz=0,f=c.forward(),r=c.right();if(k.KeyW){dx+=f.x;dz+=f.z}if(k.KeyS){dx-=f.x;dz-=f.z}if(k.KeyD){dx+=r.x;dz+=r.z}if(k.KeyA){dx-=r.x;dz-=r.z}const len=Math.hypot(dx,dz)||1;const moving=Math.abs(dx)+Math.abs(dz)>0.001;dx=dx/len*sp*dt;dz=dz/len*sp*dt;this.tryMove(dx,0,0);this.tryMove(0,0,dz);if(moving)this.walkTime+=dt*(canSprint?12:8);if(canSprint)this.stamina=Math.max(0,this.stamina-dt*18);else this.stamina=Math.min(100,this.stamina+dt*11);this.vel.y-=this.cfg.PLAYER.GRAVITY*dt;if(k.Space&&this.jump())k.Space=false;const before=this.pos.y;this.tryMove(0,this.vel.y*dt,0,true);if(this.pos.y===before&&this.vel.y<0)this.onGround=true;else if(this.vel.y>0)this.onGround=false;this.camera.position.set(this.pos.x,this.pos.y+1.62+(moving&&this.onGround?Math.sin(this.walkTime)*.025:0),this.pos.z);this.sprint=canSprint;this.hunger=Math.max(0,this.hunger-dt*(canSprint?.004:.0025));if(this.hunger<=0)this.health=Math.max(0,this.health-dt*.4);if(this.hunger>15&&this.health<20){this.regenTimer+=dt;if(this.regenTimer>8){this.regenTimer=0;this.health=Math.min(20,this.health+1)}}else this.regenTimer=0}
 tryMove(dx,dy,dz,vertical=false){const p=this.pos.clone();p.x+=dx;p.y+=dy;p.z+=dz;if(!this.collides(p)){this.pos.copy(p);return true}if(vertical)this.vel.y=0;return false}
 raycast(max=7){const o=this.camera.position.clone(),d=new THREE.Vector3();this.camera.getWorldDirection(d);let prev=null;for(let t=0;t<max;t+=.045){const p=o.clone().addScaledVector(d,t),b={x:Math.floor(p.x),y:Math.floor(p.y),z:Math.floor(p.z)},id=this.world.getBlock(b.x,b.y,b.z);if(id&&id!==BLOCK.WATER)return{block:b,id,previous:prev};prev=b}return null}
 damage(n){const armor=Object.values(this.inventory?.equipment||{}).reduce((a,id)=>a+(INFO?.[id]?.armor||0),0);const reduced=Math.max(0,n*(1-Math.min(.65,armor*.08)));this.health=Math.max(0,this.health-reduced)}
 addXP(amount=1){this.xp+=Math.max(0,amount);while(this.xp>=this.level*100){this.xp-=this.level*100;this.level++;this.health=20;this.stamina=100}return this.level}
 eat(){const s=this.inventory?.selectedItem?.();if(!s||!INFO[s.id]?.food)return false;if(!this.inventory.remove(s.id,1))return false;this.hunger=Math.min(20,this.hunger+INFO[s.id].food);return true}
}
