import {BLOCK,INFO,ITEM} from "../world/Block.js";
export class Inventory{
 constructor(){this.slots=Array.from({length:36},()=>({id:0,count:0}));this.durability=Array(36).fill(0);this.selected=0;this.equipment={weapon:0,tool:0,offhand:0,head:0,body:0,legs:0,feet:0};this.equipmentDurability={weapon:0,tool:0,offhand:0,head:0,body:0,legs:0,feet:0}}
 add(id,count=1){return this.addDetailed(id,count).remaining===0}
 addDetailed(id,count=1){let left=Math.max(0,Number(count)||0),added=0;const ranges=[[0,27],[27,36]];for(const [start,end] of ranges){for(const mode of ["merge","empty"]){for(let i=start;i<end&&left>0;i++){const s=this.slots[i];if(mode==="merge"?(s.id!==id||s.count>=64):s.id!==0)continue;const n=Math.min(left,64-s.count);s.id=id;if(INFO[id]?.durability&&!this.durability[i])this.durability[i]=INFO[id].durability;s.count+=n;left-=n;added+=n}}}return{added,remaining:left}}
 remove(id,count=1){if(!this.has(id,count))return false;for(const s of this.slots)if(s.id===id&&count>0){const n=Math.min(count,s.count);s.count-=n;count-=n;if(!s.count){const i=this.slots.indexOf(s);s.id=0;this.durability[i]=0}}return true}
 has(id,count=1){return this.slots.reduce((a,s)=>a+(s.id===id?s.count:0),0)>=count}
 selectedItem(){return this.slots[27+this.selected]}
 equipmentItem(slot){return this.equipment[slot]||0}
 equipFromInventory(index,slot){const s=this.slots[index];if(!s?.id)return false;const info=INFO[s.id];if(!info?.item||!slot)return false;const allowed={weapon:["sword"],tool:["pick","axe","hoe","shovel"],offhand:[]};if(allowed[slot]&&allowed[slot].length&&!allowed[slot].includes(info.tool))return false;if(["head","body","legs","feet"].includes(slot)&&!info.armorSlot)return false;const old=this.equipment[slot]||0,oldDur=this.equipmentDurability[slot]||0;this.equipment[slot]=s.id;this.equipmentDurability[slot]=this.durability[index]||INFO[s.id]?.durability||0;s.count--;if(s.count<=0){s.id=0;this.durability[index]=0;}if(old){this.add(old,1);const ni=this.slots.findIndex(x=>x.id===old&&x.count>0);if(ni>=0)this.durability[ni]=oldDur||INFO[old]?.durability||0;}if(index>=27)this.selected=index-27;return true}
 unequip(slot){const id=this.equipment[slot]||0;if(!id)return false;if(!this.add(id,1))return false;this.equipment[slot]=0;this.equipmentDurability[slot]=0;return true}
 serialize(){return{selected:this.selected,durability:[...this.durability],equipmentDurability:{...this.equipmentDurability},slots:this.slots.map(s=>({id:s.id,count:s.count})),equipment:{...this.equipment}}}
 deserialize(data){if(!data?.slots)return;this.slots=Array.from({length:36},(_,i)=>({id:data.slots[i]?.id||0,count:data.slots[i]?.count||0}));this.durability=Array.from({length:36},(_,i)=>Number(data.durability?.[i]||0));this.selected=Math.max(0,Math.min(8,data.selected|0));if(!this.slots.slice(27).some(s=>s.id)&&this.slots.slice(0,9).some(s=>s.id)){for(let i=0;i<9;i++){this.slots[27+i]={...this.slots[i]};this.slots[i]={id:0,count:0};this.durability[27+i]=this.durability[i];this.durability[i]=0}}this.equipment={weapon:data.equipment?.weapon||0,tool:data.equipment?.tool||0,offhand:data.equipment?.offhand||0,head:data.equipment?.head||0,body:data.equipment?.body||0,legs:data.equipment?.legs||0,feet:data.equipment?.feet||0};this.equipmentDurability={weapon:Number(data.equipmentDurability?.weapon||0),tool:Number(data.equipmentDurability?.tool||0),offhand:Number(data.equipmentDurability?.offhand||0),head:Number(data.equipmentDurability?.head||0),body:Number(data.equipmentDurability?.body||0),legs:Number(data.equipmentDurability?.legs||0),feet:Number(data.equipmentDurability?.feet||0)}}
 getMiningTool(){const eq=this.equipment.tool;if(eq&&INFO[eq]?.tool)return {id:eq,info:INFO[eq],durability:this.equipmentDurability.tool||INFO[eq].durability||0,slot:"tool"};const s=this.selectedItem();if(s?.id&&INFO[s.id]?.tool){const i=27+this.selected;return {id:s.id,info:INFO[s.id],durability:this.durability[i]||INFO[s.id].durability||0,slot:i};}return {id:0,info:null,durability:0,slot:null}}
 damageMiningTool(amount=1){const t=this.getMiningTool();if(!t.id||!t.info?.durability)return true;let d=Math.max(0,t.durability-amount);if(t.slot==="tool"){this.equipmentDurability.tool=d;if(d<=0)this.equipment.tool=0}else{this.durability[t.slot]=d;if(d<=0){this.slots[t.slot].id=0;this.slots[t.slot].count=0}}return d>0}
}
export const RECIPES=[
{name:"Доски ×4",out:{id:10,count:4},in:[{id:6,count:1}]},{name:"Палки ×4",out:{id:ITEM.STICK,count:4},in:[{id:10,count:2}]},{name:"Кирка",out:{id:ITEM.WOOD_PICK,count:1},in:[{id:10,count:3},{id:ITEM.STICK,count:2}]},{name:"Лопата",out:{id:ITEM.WOOD_SHOVEL,count:1},in:[{id:10,count:1},{id:ITEM.STICK,count:2}]},{name:"Алмазная кирка",out:{id:ITEM.DIAMOND_PICK,count:1},in:[{id:130,count:3},{id:ITEM.STICK,count:2}]},{name:"Каменная кирка",out:{id:ITEM.STONE_PICK,count:1},in:[{id:3,count:3},{id:ITEM.STICK,count:2}]},{name:"Железная кирка",out:{id:ITEM.IRON_PICK,count:1},in:[{id:9,count:3},{id:ITEM.STICK,count:2}]},{name:"Топор",out:{id:ITEM.WOOD_AXE,count:1},in:[{id:10,count:3},{id:ITEM.STICK,count:2}]},{name:"Меч",out:{id:ITEM.SWORD,count:1},in:[{id:3,count:2},{id:ITEM.STICK,count:1}]},{name:"Факел ×4",out:{id:ITEM.TORCH,count:4},in:[{id:ITEM.STICK,count:1},{id:8,count:1}]},{name:"Фонарь",out:{id:ITEM.LANTERN,count:1},in:[{id:ITEM.TORCH,count:1},{id:10,count:1}]},{name:"Хлеб ×2",out:{id:ITEM.BREAD,count:2},in:[{id:6,count:1}]},{name:"Сундук",out:{id:ITEM.CHEST,count:1},in:[{id:10,count:8}]},{name:"Костёр",out:{id:ITEM.CAMPFIRE,count:1},in:[{id:6,count:3},{id:ITEM.STICK,count:3},{id:8,count:1}]},{name:"Печь",out:{id:24,count:1},in:[{id:3,count:8}]},{name:"Булыжник ×2",out:{id:21,count:2},in:[{id:3,count:2}]},{name:"Мох ×2",out:{id:19,count:2},in:[{id:2,count:1},{id:7,count:1}]},{name:"Мотыга",out:{id:ITEM.HOE,count:1},in:[{id:10,count:2},{id:ITEM.STICK,count:2}]},{name:"Яблоко",out:{id:ITEM.APPLE,count:1},in:[{id:6,count:1}]},{name:"Кожа ×2",out:{id:ITEM.LEATHER,count:2},in:[{id:ITEM.RAW_MEAT,count:1}]},{name:"Кожаный шлем",out:{id:ITEM.LEATHER_HELM,count:1},in:[{id:ITEM.LEATHER,count:5}]},{name:"Кожаная куртка",out:{id:ITEM.LEATHER_CHEST,count:1},in:[{id:ITEM.LEATHER,count:8}]},{name:"Кожаные поножи",out:{id:ITEM.LEATHER_LEGS,count:1},in:[{id:ITEM.LEATHER,count:7}]},{name:"Кожаные ботинки",out:{id:ITEM.LEATHER_BOOTS,count:1},in:[{id:ITEM.LEATHER,count:4}]},{name:"Щит",out:{id:ITEM.SHIELD,count:1},in:[{id:ITEM.LEATHER,count:5},{id:10,count:3}]}];
export function craft(inv,r){for(const x of r.in)if(!inv.has(x.id,x.count))return false;for(const x of r.in)inv.remove(x.id,x.count);return inv.add(r.out.id,r.out.count)}
