import THREE from "../three.js";
import {INFO,ICON} from "../world/Block.js";
import {getItemData,createItemStack,cloneItemStack} from "./ItemData.js";
import {craftGrid,getCraftResult} from "./Crafting.js";
import {InputManager} from "./InputManager.js";

export class InventoryUI{
 constructor(game){this.game=game;this.inv=game?.inventory||null;this.input=new InputManager();this.input.attachKeyboard();this.cursor=createItemStack();this.mobileMode="whole";this.longPressTimer=null;this.preview=null;this.previewRAF=0;this.lastRender="";this.previewReady=false}
 setupPreview(){if(this.previewReady)return;const host=document.getElementById("inventoryPreview3D");if(!host)return;try{this.previewRenderer=new THREE.WebGLRenderer({alpha:true,antialias:false,powerPreference:"low-power"});this.previewRenderer.setPixelRatio(Math.min(devicePixelRatio||1,1.25));this.previewRenderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight),false);this.previewRenderer.outputColorSpace=THREE.SRGBColorSpace;host.innerHTML="";host.appendChild(this.previewRenderer.domElement);this.previewScene=new THREE.Scene();this.previewScene.add(new THREE.HemisphereLight(0xffffff,0x34413a,1.8));this.previewScene.add(new THREE.DirectionalLight(0xffffff,1.6));this.previewCamera=new THREE.PerspectiveCamera(28,host.clientWidth/Math.max(1,host.clientHeight),.1,50);this.previewCamera.position.set(0,1.25,5.2);this.previewAvatar=new THREE.Group();this.previewScene.add(this.previewAvatar);this.buildAvatar();this.previewResizeObserver=new ResizeObserver(()=>this.resizePreview());this.previewResizeObserver.observe(host);this.previewReady=true;this.renderPreview();}catch(e){this.previewReady=false;host.textContent="3D preview unavailable";console.warn("Inventory preview disabled",e)}}
 buildAvatar(){const S=THREE;const mat=(c)=>new S.MeshLambertMaterial({color:c});const box=(w,h,d,c)=>{const m=new S.Mesh(new S.BoxGeometry(w,h,d),mat(c));this.previewAvatar.add(m);return m};this.avatarParts={};this.avatarParts.legsL=box(.28,.75,.28,0x39454a);this.avatarParts.legsL.position.set(-.17,.38,0);this.avatarParts.legsR=box(.28,.75,.28,0x39454a);this.avatarParts.legsR.position.set(.17,.38,0);this.avatarParts.body=box(.68,.8,.36,0x5c6b70);this.avatarParts.body.position.y=1.1;this.avatarParts.head=box(.48,.48,.48,0xc99b79);this.avatarParts.head.position.y=1.75;this.avatarParts.armL=box(.22,.72,.25,0xc18d6e);this.avatarParts.armL.position.set(-.48,1.1,0);this.avatarParts.armR=box(.22,.72,.25,0xc18d6e);this.avatarParts.armR.position.set(.48,1.1,0);const shadow=new S.Mesh(new S.CircleGeometry(.65,24),new S.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.25}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.01;this.previewScene.add(shadow);this.avatarParts.shadow=shadow}
 renderPreview(){if(!this.previewRenderer||!this.previewScene||!this.game.inventoryOpen)return;this.previewAvatar.rotation.y+=0.004;this.updatePreviewEquipment();this.previewRenderer.render(this.previewScene,this.previewCamera);this.previewRAF=requestAnimationFrame(()=>this.renderPreview())}
 updatePreviewEquipment(){if(!this.avatarParts)return;const slots=this.inv.equipment||{};this.avatarParts.head.material.color.setHex(slots.head?0x5b8b9a:0xc99b79);this.avatarParts.body.material.color.setHex(slots.body?0x35566d:0x5c6b70);this.avatarParts.legsL.material.color.setHex(slots.legs?0x41546c:0x39454a);this.avatarParts.legsR.material.color.setHex(slots.legs?0x41546c:0x39454a);this.avatarParts.armL.material.color.setHex(slots.offhand?0x6b7e84:0xc18d6e);this.avatarParts.armR.material.color.setHex(slots.weapon||slots.tool?0x6b7e84:0xc18d6e)}
 resizePreview(){const h=document.getElementById("inventoryPreview3D");if(!h||!this.previewRenderer)return;const w=Math.max(1,h.clientWidth),hh=Math.max(1,h.clientHeight);this.previewRenderer.setSize(w,hh,false);this.previewCamera.aspect=w/hh;this.previewCamera.updateProjectionMatrix()}
 destroy(){cancelAnimationFrame(this.previewRAF);this.previewResizeObserver?.disconnect();this.previewRenderer?.dispose()}
 open(){if(!this.game||!this.inv)return;this.setupPreview();this.game.inventoryOpen=true;this.game.running=false;document.exitPointerLock?.();document.body.classList.add("inventory-open");this.cursor=createItemStack();this.mobileMode="whole";document.getElementById("inventoryPanel")?.classList.remove("hidden");this.render();this.renderPreview()}
 close(){if(!this.game)return;this.returnCraftItems();this.cursorToInventoryOrDrop();this.game.craftMode="player";this.game.inventoryOpen=false;document.body.classList.remove("inventory-open");document.getElementById("inventoryPanel")?.classList.add("hidden");this.game.running=true;if(!matchMedia("(pointer:coarse)").matches)this.game.renderer.domElement.requestPointerLock?.();cancelAnimationFrame(this.previewRAF);this.game.save?.()}
 cursorToInventoryOrDrop(){if(!this.cursor?.id||!this.cursor?.count)return;const result=this.inv.addDetailed(this.cursor.id,this.cursor.count);if(result.remaining>0)this.dropIntoWorld(this.cursor.id,result.remaining);this.cursor=createItemStack()}
 returnCraftItems(){const grid=this.game.craftMode==="table"?this.game.craftGrid3:this.game.craftGrid2;if(!grid)return;for(const s of grid){if(!s.id||!s.count)continue;const id=s.id,count=s.count;const result=this.inv.addDetailed(id,count);if(result.remaining>0)this.dropIntoWorld(id,result.remaining);s.id=0;s.count=0}}
 dropIntoWorld(id,count){if(!count)return;const p=this.game.player.pos.clone();this.game.mining?.spawnDrop?.(id,count,{x:Math.floor(p.x),y:Math.floor(p.y),z:Math.floor(p.z)});this.game.audio?.block?.()}
 stackMax(id){return getItemData(id).max_stack||64}
 same(a,b){return !!a?.id&&a.id===b?.id}
 takeWhole(index){const s=this.inv.slots[index];if(!s?.id)return false;this.cursor=createItemStack(s.id,s.count);s.id=0;s.count=0;this.inv.durability[index]=0;return true}
 takeHalf(index){const s=this.inv.slots[index];if(!s?.id)return false;const n=Math.ceil(s.count/2);this.cursor=createItemStack(s.id,n);s.count-=n;if(!s.count){s.id=0;this.inv.durability[index]=0}return true}
 place(index,amount=this.cursor.count){if(!this.cursor.id||amount<=0)return false;const s=this.inv.slots[index];if(s.id&&s.id!==this.cursor.id)return false;const max=this.stackMax(this.cursor.id),space=max-(s.count||0),n=Math.min(space,amount);if(n<=0)return false;s.id=this.cursor.id;s.count=(s.count||0)+n;this.cursor.count-=n;if(!this.cursor.count)this.cursor=createItemStack();return true}
 swap(index){const old=cloneItemStack(this.inv.slots[index]);this.inv.slots[index]=createItemStack(this.cursor.id,this.cursor.count);this.cursor=old;return true}
 moveShift(index){const sourceHot=index>=27;if(sourceHot){for(let i=0;i<27;i++){if(this.tryMergeOrEmpty(index,i))return true}}else{for(let i=27;i<36;i++){if(this.tryMergeOrEmpty(index,i))return true}}return false}
 tryMergeOrEmpty(from,to){const a=this.inv.slots[from],b=this.inv.slots[to];if(!a?.id)return false;if(b.id&&b.id!==a.id)return false;const max=this.stackMax(a.id),space=max-(b.count||0);if(space<=0)return false;const n=Math.min(space,a.count);if(!b.id)b.id=a.id;b.count=(b.count||0)+n;a.count-=n;if(!a.count){a.id=0;this.inv.durability[from]=0}return true}
 handleInventorySlot(index,e){if(!this.game.inventoryOpen)return;if(e.shiftKey&&!this.isTouch(e)){this.moveShift(index);if(index>=27)this.inv.selected=index-27;this.render();return}const s=this.inv.slots[index];if(this.isTouch(e)){this.mobileTransfer(()=>this.transferSlot(index));if(index>=27)this.inv.selected=index-27;return}if(e.button===2){if(!this.cursor.id){this.takeHalf(index)}else if(s.id===this.cursor.id){this.place(index,1)}this.render();return}if(e.button===0){if(!this.cursor.id)this.takeWhole(index);else if(!s.id||s.id===this.cursor.id)this.place(index);else this.swap(index);if(index>=27)this.inv.selected=index-27;this.render()}}
 transferSlot(index){const s=this.inv.slots[index];if(!this.cursor.id){if(this.mobileMode==="half")this.takeHalf(index);else this.takeWhole(index);return true}if(!s.id||s.id===this.cursor.id)return this.place(index,this.mobileMode==="one"?1:this.cursor.count);return this.swap(index)}
 mobileTransfer(fn){fn();this.render()}
 isTouch(e){return e.pointerType==="touch"||e.pointerType==="pen"}
 bindSlot(el,handler){this.input.bindPointer(el,{down:e=>{e.preventDefault();e.stopPropagation();this.longPressTimer=setTimeout(()=>{if(this.isTouch(e)){this.mobileMode="half";handler(e);this.longPressTimer=null}},420)},up:e=>{e.preventDefault();e.stopPropagation();if(this.longPressTimer){clearTimeout(this.longPressTimer);this.longPressTimer=null;handler(e)}},cancel:()=>{clearTimeout(this.longPressTimer);this.longPressTimer=null}})}
 render(){if(!this.game.inventoryOpen)return;const grid=document.getElementById("inventoryGrid"),hot=document.getElementById("inventoryHotbarGrid");const make=(parent,start,end)=>{if(!parent)return;parent.innerHTML="";for(let i=start;i<end;i++){const s=this.inv.slots[i],d=document.createElement("button");d.type="button";d.className="invSlot"+(i>=27&&i-27===this.inv.selected?" selected":"")+(this.cursor.id?" cursorActive":"");d.dataset.index=i;d.innerHTML=`<span class="slotIcon">${s.id?ICON[s.id]||"·":""}</span><small>${s.count||""}</small>`;d.title=s.id?`${INFO[s.id]?.name||"Предмет"} • ${s.count}`:"Пусто";this.bindSlot(d,e=>this.handleInventorySlot(i,e));parent.appendChild(d)}};make(grid,0,27);make(hot,27,36);this.renderCraft();this.renderCursor();this.renderInfo();this.updatePreviewEquipment()}
 renderCursor(){const c=document.getElementById("inventoryCursorStack");if(!c)return;c.textContent=this.cursor.id?`${ICON[this.cursor.id]||"·"} ×${this.cursor.count}`:"Курсор: пусто";c.classList.toggle("active",!!this.cursor.id)}
 renderInfo(){const s=this.inv.selectedItem(),el=document.getElementById("inventorySelectedInfo");if(el)el.textContent=s?.id?`${INFO[s.id]?.name||"Предмет"} ×${s.count}`:"Пусто";const held=document.getElementById("inventoryHeldName");if(held)held.textContent=`Рука: ${s?.id?(INFO[s.id]?.name||"предмет"):"пусто"}`}
 renderCraft(){const grid=this.game.craftMode==="table"?this.game.craftGrid3:this.game.craftGrid2;const el=document.getElementById("craftGrid");if(!el||!grid)return;el.className=`craftGrid ${grid.length===9?"grid3":"grid2"}`;el.innerHTML="";grid.forEach((s,i)=>{const b=document.createElement("button");b.type="button";b.className="craftCell";b.innerHTML=`<span>${s.id?ICON[s.id]||"·":""}</span><small>${s.count||""}</small>`;this.bindSlot(b,e=>this.handleCraftSlot(i,e));el.appendChild(b)});const out=getCraftResult(grid,this.game.getCurrentRecipes()),o=document.getElementById("craftOutput");if(o){o.innerHTML=out?`<span>${ICON[out.recipe.out.id]||"·"}</span><strong>${INFO[out.recipe.out.id]?.name||"Предмет"}</strong><small>×${out.recipe.out.count}</small>`:`<span>→</span><strong>Нет результата</strong>`;o.classList.toggle("ready",!!out);o.onclick=e=>{e.preventDefault();if(out)this.takeCraft(out)}}const title=document.getElementById("craftTitle");if(title)title.textContent=grid.length===9?"ВЕРСТАК • 3×3":"КРАФТ • 2×2"}
 bindOnce(el,key,fn){if(el.dataset.bound===key)return;el.dataset.bound=key;el.onclick=fn}
 handleCraftSlot(index,e){const grid=this.game.craftMode==="table"?this.game.craftGrid3:this.game.craftGrid2,s=grid[index];if(this.isTouch(e)){if(!this.cursor.id){if(!s.id)return;this.cursor=createItemStack(s.id,this.mobileMode==="half"?Math.ceil(s.count/2):s.count);s.count-=this.cursor.count;if(!s.count)s.id=0}else if(!s.id||s.id===this.cursor.id){const max=this.stackMax(this.cursor.id),n=Math.min(max-(s.count||0),this.mobileMode==="one"?1:this.cursor.count);s.id=this.cursor.id;s.count=(s.count||0)+n;this.cursor.count-=n;if(!this.cursor.count)this.cursor=createItemStack()}else{const old=cloneItemStack(s);s.id=this.cursor.id;s.count=this.cursor.count;this.cursor=old}this.render();return}if(e.button===2){if(!this.cursor.id&&s.id){const n=Math.ceil(s.count/2);this.cursor=createItemStack(s.id,n);s.count-=n;if(!s.count)s.id=0}else if(this.cursor.id===s.id){s.count++;this.cursor.count--;if(!this.cursor.count)this.cursor=createItemStack()}this.render();return}if(!this.cursor.id&&s.id){this.cursor=createItemStack(s.id,s.count);s.id=0;s.count=0}else if(this.cursor.id&&(!s.id||s.id===this.cursor.id)){const n=Math.min(this.stackMax(this.cursor.id)-(s.count||0),this.cursor.count);s.id=this.cursor.id;s.count=(s.count||0)+n;this.cursor.count-=n;if(!this.cursor.count)this.cursor=createItemStack()}else if(this.cursor.id){const old=cloneItemStack(s);s.id=this.cursor.id;s.count=this.cursor.count;this.cursor=old}this.render()}
 takeCraft(out){if(!out)return;const result=out.recipe.out;if(this.cursor.id&&this.cursor.id!==result.id)return;const max=this.stackMax(result.id);if((this.cursor.count||0)+result.count>max)return;const grid=this.game.craftMode==="table"?this.game.craftGrid3:this.game.craftGrid2;const dummy={has:()=>true,remove:()=>true,add:()=>true};if(!craftGrid(grid,out.recipe,dummy))return;if(!this.cursor.id)this.cursor=createItemStack(result.id,result.count);else this.cursor.count+=result.count;this.game.audio?.block?.();this.render()}
 setMobileMode(mode){this.mobileMode=mode==="one"?"one":mode==="half"?"half":"whole";document.querySelectorAll("[data-stack-mode]").forEach(b=>b.classList.toggle("active",b.dataset.stackMode===this.mobileMode))}
 setupModeButtons(){document.querySelectorAll("[data-stack-mode]").forEach(b=>b.addEventListener("click",e=>{e.preventDefault();this.setMobileMode(b.dataset.stackMode)}));this.setMobileMode("whole")}
}
